### ISSUE TITLE
Can't easily access settings..

### ISSUE THREAD

**Issue by mistyn8** [daemonLibra/Jira-Snippet#7]
![image](https://github.com/daemonLibra/Jira-Snippet/assets/12418214/e04016be-baf2-495a-8462-6e041195a75d)

**Comment by daemonLibra** [comment]
jep that looks not right, it should defninitly be larger in witdh. Which browser are u using, so that i can replicate the issue?

**Comment by mistyn8** [comment]
latest edge..
![image](https://github.com/daemonLibra/Jira-Snippet/assets/12418214/a2b40955-19be-4a78-96ef-c56af7c783fc)

**Comment by kngbong** [comment]
This issue is still reproducible.
Devices: Ubuntu 23.04, Win 10.
Browsers: Chrome 117.0.5938.132, Edge 117.0.2045.47

**Comment by Dalle75** [comment]
Reproduceable on Mac OS 14.2.1
Chrome 120.0.6099.234

**Comment by cord-agencyroot** [comment]
Having the same issue on latest version of Arc browser as well

**Comment by daemonLibra** [comment]
I updated Chrome and Edge. The settings dialog should be accessible after first tests.
